// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFBR.Log.Api.Infrastructure;

namespace SFBR.Log.Api.Migrations
{
    [DbContext(typeof(LogContext))]
    partial class LogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SFBR.Log.Api.Model.ActionLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<string>("ActionDesciption");

                    b.Property<DateTime>("ActionTime");

                    b.Property<string>("ApiUrl");

                    b.Property<string>("ApplicationContext");

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("DeviceCode");

                    b.Property<string>("DeviceName");

                    b.Property<string>("FunctionName");

                    b.Property<string>("Name");

                    b.Property<string>("Paramaters");

                    b.HasKey("Id");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("SFBR.Log.Api.Model.AlarmLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlarmCode");

                    b.Property<int>("AlarmFrom");

                    b.Property<int>("AlarmLevel");

                    b.Property<string>("AlarmName");

                    b.Property<string>("AlarmStatus");

                    b.Property<DateTime>("AlarmTime");

                    b.Property<int>("AlarmType");

                    b.Property<string>("AlarmedDescription");

                    b.Property<string>("AlarmingDescription");

                    b.Property<int>("ClearReason");

                    b.Property<DateTime?>("ClearTime");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("DeviceId");

                    b.Property<string>("DisposalContent")
                        .HasMaxLength(400);

                    b.Property<DateTime?>("DisposalTime");

                    b.Property<string>("DisposalUser")
                        .HasMaxLength(50);

                    b.Property<string>("DisposalUserName")
                        .HasMaxLength(50);

                    b.Property<bool>("Disposed");

                    b.Property<string>("EquipNum");

                    b.Property<string>("GroupName");

                    b.Property<bool>("IsClear");

                    b.Property<bool>("IsStatistics");

                    b.Property<double?>("LowerLimit");

                    b.Property<double?>("RealData");

                    b.Property<double>("RepairTime");

                    b.Property<string>("TargetCode");

                    b.Property<double?>("UpperLimit");

                    b.HasKey("Id");

                    b.ToTable("AlarmLogs");
                });

            modelBuilder.Entity("SFBR.Log.Api.Model.Device", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceName");

                    b.Property<string>("DeviceTypeCode");

                    b.Property<string>("EquipNum");

                    b.Property<string>("ModelCode");

                    b.Property<string>("ParentId");

                    b.Property<string>("RegionCode");

                    b.Property<string>("RegionId");

                    b.Property<string>("RegionName");

                    b.Property<string>("TentantId");

                    b.Property<string>("TentantName");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
